<?php

namespace AppBundle\Repository;

/**
 * ThemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemesRepository extends \Doctrine\ORM\EntityRepository
{
}
