pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

categorieProduits:
  path:  /categorie/{categorie}
  defaults: { _controller: AppBundle:Default:categorie }

rechercheProduits:
  path:  /recherche
  defaults: { _controller: AppBundle:Default:rechercheTraitement }