# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

        Symfony\Component\Security\Core\User\User: plaintext
        Blog\BlogBundle\Entity\Author:
          algorithm: sha1
          iterations: 1
          encode_as_base64: false


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory_provider:
          memory:
            users:
              admin: {password: 123, roles: ['ROLE_ADMIN']}
              god: {password: 777, roles: ['ROLE_SUPER_ADMIN']}

        author_provider:
            entity: {class: Blog\BlogBundle\Entity\Author, property: email}

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        author:
            pattern: ^/author
            provider: author_provider
            form_login:
                login_path: author_login
                check_path: author_login_check
                default_target_path: /author/new-article

        admin:
            pattern: ^/admin
            provider: in_memory_provider
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: /admin

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }